### ISSUE TITLE
Investigate Krombacher connection errors

### ISSUE THREAD

**Issue by MykytaDuniashev** [elasticio/amqp-component#22]
## Description

Krombacher reported that their [flow](https://app.elastic.io/c/5f350c8df8392d00111c1c40/w/5f350ced82be0b0011871e02/designer/640af39b1a545c00120b3bba/v/latest) stopped working on 1/08/2023, around 15k messages were stuck there until Friday 4/08/2023. We restarted the pods by suspending/unsuspending the flow and messages were processed. There were no reports from the Krombacher of any connection errors since we fixed this problem with our latest version (27/03/2023).

[Logs](https://app.elastic.io/c/5f350c8df8392d00111c1c40/w/5f350ced82be0b0011871e02/logs?from=2023-07-31T21%3A00%3A00Z&to=2023-08-07T20%3A59%3A59Z&flowIds=640af39b1a545c00120b3bba&levels=50&limit=200&offset=0) 1/08/2023 GMT+3:

```
1 Aug, 2023 11:16:07.528 
PC - Loyalty Consumer - V2
3. Pub krombacher.user#loyalty
Error
Unexpected connection close.

1 Aug, 2023 11:16:07.527 
PC - Loyalty Consumer - V2
3. Pub krombacher.user#loyalty
Error
AMQP read Connection error

1 Aug, 2023 11:16:07.504 
PC - Loyalty Consumer - V2
Mapper
info
Error
Unexpected connection close.

1 Aug, 2023 11:16:07.504
PC - Loyalty Consumer - V2
Mapper
info
Error
AMQP read Connection error

1 Aug, 2023 11:15:37.959
PC - Loyalty Consumer - V2
3. Pub krombacher.user#loyalty
Error
Failed on publishing message to queue

1 Aug, 2023 11:15:37.958
PC - Loyalty Consumer - V2
3. Pub krombacher.user#loyalty
Error
AMQP Connection error

1 Aug, 2023 11:15:37.848
PC - Loyalty Consumer - V2
3. Pub krombacher.user#loyalty
Error
AMQP Connection error

1 Aug, 2023 11:15:37.733
PC - Loyalty Consumer - V2
3. Pub krombacher.user#loyalty
Error
AMQP Connection error

1 Aug, 2023 11:15:37.621
PC - Loyalty Consumer - V2
3. Pub krombacher.user#loyalty
Error
AMQP Connection error

1 Aug, 2023 11:15:26.704
PC - Loyalty Consumer - V2
3. Pub krombacher.user#loyalty
Error
Unexpected connection close.

1 Aug, 2023 11:15:26.640
PC - Loyalty Consumer - V2
3. Pub krombacher.user#loyalty
Error
AMQP write Connection error

1 Aug, 2023 11:15:26.625
PC - Loyalty Consumer - V2
1. krombacher.loyalty.v1
Error
Unexpected connection close.

1 Aug, 2023 11:15:26.610
PC - Loyalty Consumer - V2
1. krombacher.loyalty.v1
Error
AMQP write Connection error

1 Aug, 2023 11:15:26.564
PC - Loyalty Consumer - V2
Mapper
Error
Unexpected connection close.

1 Aug, 2023 11:15:26.557
PC - Loyalty Consumer - V2
Mapper
Error
AMQP read Connection error
```
**Note:** Contact support to gain access to their [workspace](https://app.elastic.io/c/5f350c8df8392d00111c1c40/w/5f350ced82be0b0011871e02).

## Definition of Done

- [ ] Find out if it was a problem with our component or an external problem?

**Comment by andrewreshitko** [comment]
Seems Error `AMQP read Connection error` is related to Platform (possibly happens in RMQ).

**Comment by andrewreshitko** [comment]
Need review from Platform side.

**Comment by Legendmiha** [comment]
Investigation results from Platform side:
During deployment of Platform version 23.31 for some reason (still unknown) 2 out of 3 instances of haproxy service were restarted, which dropped connection to RabbitMQ for all Sailors that were connected to those 2 instances.
Looking through logs, we can see that all of the sailors successfully reconnected to haproxy instance that was running, but the Sailor inside the pod with AMQP Component tried to reconnect 3 times and then threw an error.
Now, the expected behaviour is that the pod where uncaught error was thrown is restarted with exponential timeout between restarts.
The only way to see what happened with the pod is to look through admiral logs, but the actual logs were already cleared from Graylog (TTL 7.5 days). So there is no way of knowing what was happening there.

Our suggestion if this happens again - to contact FF as soon as possible to have a better chance of finding out what happened.

**Comment by A3a3e1** [comment]
@Legendmiha  Is there any way for the support team to set up monitoring or any kind of alert to be informed as soon as possible?

**Comment by MykytaDuniashev** [comment]
@A3a3e1 We already have an alert for messages stuck in the queues. Since this issue occurred during deployment, support will monitor Krombacher flows during the next releases to avoid hanging messages and have a better chance of figuring out what happened. The customer has also been informed and will let us know if they encounter this issue again.

**Comment by MykytaDuniashev** [comment]
I see a lot of AMQP errors in logs today, all occurred at 11:08.
![image](https://github.com/elasticio/amqp-component/assets/108279772/3aa4a490-2e01-4376-8368-bca273a44941)
The last time they had it was 25 September.
![image](https://github.com/elasticio/amqp-component/assets/108279772/48b09ebb-84a3-48aa-b609-3dc5c1cfdc1e)
BTW, no erroneous executions, stuck flows, or complaints from Krombacher. 
I will continue to monitor.

**Comment by MykytaDuniashev** [comment]
Definitely these errors appear during deployment.
![image](https://github.com/elasticio/amqp-component/assets/108279772/02d59397-2f74-46ba-9ce5-4953f8016a89)
The situation is the same as yesterday, Krombacher flows look fine.

**Comment by MykytaDuniashev** [comment]
Since the 23.39.1 release, there have been no more AMQP errors caught. There were no disruptions to customer flows. I believe that the problem has been resolved. Krombacher is also glad that this release was successful ([feedback](https://app.intercom.com/a/inbox/qgp8r7fl/inbox/shared/all/conversation/10951100096661)).

Last errors:
![image](https://github.com/elasticio/amqp-component/assets/108279772/9ff4892d-6f9b-47a2-8ec3-842fc5f3d17a)
