### ISSUE TITLE
Rework the logic of AMQP executions

### ISSUE THREAD

**Issue by erroneous0ne** [elasticio/amqp-component#24]
## Description

Krombacher wants to make the [AMQP](https://github.com/elasticio/amqp-component) component more convenient to use. Currently, each scheduled flow execution will create a record in the Executions list with no messages and no logs inside. All the logs and emitted messages will appear in the first execution. This is inconvenient for error handling, and the problem is we store executions for [30 days](https://docs.elastic.io/guides/platform-behavior.html#:~:text=30d-,Executions%20TTL,-The%20number%20of), so after a month passes this execution will be lost. 

## Component Version

1.4.2

# Definition of Done

- [ ] Introducing the new logic of executions

**Comment by HannaTrotsenko** [comment]
https://github.com/elasticio/amqp-component/releases/tag/1.4.3
